use std::path::{Path, PathBuf};

/// Render seconds since the epoch as UTC at second precision, with dashes for colons
fn iso_utc(sec: i64) -> String {
    let ts = jiff::Timestamp::from_second(sec).unwrap_or_else(|_| {
        let clamped = if sec < 0 {
            jiff::Timestamp::MIN
        } else {
            jiff::Timestamp::MAX
        };
        tracing::warn!("timestamp {sec}s since the epoch is out of range; clamping to {clamped}");
        clamped
    });
    ts.strftime("%Y-%m-%dT%H-%M-%SZ").to_string()
}

/// Render a filename given various parameters.
pub fn render(index: u64, interface: &str, sec: i64, ext: &str) -> String {
    format!("i{index:04}_{interface}_{}.{ext}", iso_utc(sec))
}

/// Scan the given directory for files matching candumpr's filename template generated by [render]
///
/// Results will be sorted in increasing order by the index.
pub fn scan<P: AsRef<Path>>(dir: P, interface: &str) -> Vec<(u64, PathBuf)> {
    let dir = dir.as_ref();
    let entries = match std::fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(e) => {
            // A directory that does not exist yet is the ordinary first-run case, not an error.
            if e.kind() != std::io::ErrorKind::NotFound {
                tracing::error!(
                    dir = %dir.display(),
                    "failed to scan for log files: {e:?}"
                );
            }
            return Vec::new();
        }
    };
    let mut logs: Vec<(u64, PathBuf)> = entries
        .flatten()
        .filter_map(|entry| {
            let index = parse_index(entry.file_name().to_str()?, interface)?;
            Some((index, entry.path()))
        })
        .collect();
    logs.sort_unstable();
    logs
}

/// Parse the index out of a log file generated by [render]
fn parse_index(name: &str, interface: &str) -> Option<u64> {
    // i<index>_<interface>_<timestamp>.<ext>
    let (index, rest) = name.strip_prefix('i')?.split_once('_')?;
    let rest = rest.strip_prefix(interface)?;
    if !rest.starts_with('_') {
        return None;
    }
    index.parse().ok()
}

/// Scan for files in the given directory, and return the next available index
pub fn next_index_in<P: AsRef<Path>>(dir: P, interface: &str) -> u64 {
    let candidates = scan(dir, interface);
    if let Some((index, path)) = candidates.last() {
        tracing::debug!(path = %path.display(), "Found previous file with index {index}");
        index.saturating_add(1) // If we got all the way to u64::MAX ... that's impressive
    } else {
        tracing::debug!("Did not find previous file; using index 0");
        0
    }
}

#[cfg(test)]
mod tests {
    use tempfile::TempDir;

    use super::*;

    /// Create empty files in `dir`.
    fn touch(dir: &Path, files: &[&str]) {
        for file in files {
            std::fs::write(dir.join(file), b"").unwrap();
        }
    }

    /// Indices and filenames of a scan result, for readable assertions.
    fn indexed_names(logs: &[(u64, PathBuf)]) -> Vec<(u64, &str)> {
        logs.iter()
            .map(|(index, path)| (*index, path.file_name().unwrap().to_str().unwrap()))
            .collect()
    }

    #[test]
    fn iso_utc_renders_and_clamps() {
        let vectors = [
            (0, "1970-01-01T00-00-00Z"),
            (1732117385, "2024-11-20T15-43-05Z"),
            (-86400, "1969-12-31T00-00-00Z"),
            (i64::MIN, "-9999-01-02T01-59-59Z"),
            (i64::MAX, "9999-12-30T22-00-00Z"),
        ];
        for (sec, expected) in vectors {
            assert_eq!(iso_utc(sec), expected, "sec={sec}");
        }
    }

    #[test]
    fn render_filename() {
        assert_eq!(
            render(0, "can0", 1732117385, "log"),
            "i0000_can0_2024-11-20T15-43-05Z.log"
        );
        // The index pads to width 4 and keeps counting past 9999 as plain decimal.
        assert_eq!(
            render(10000, "vcan1", 0, "pcap"),
            "i10000_vcan1_1970-01-01T00-00-00Z.pcap"
        );
    }

    #[test]
    fn parse_index_reads_back_what_render_writes() {
        for index in [0, 7, 10000, u64::MAX] {
            let name = render(index, "can0", 1732117385, "log");
            assert_eq!(parse_index(&name, "can0"), Some(index), "name={name}");
        }
    }

    #[test]
    fn parse_index_matches_the_scheme_ignoring_the_extension() {
        let vectors = [
            ("i0000_can0_2024-11-20T15-43-05Z.log", "can0", Some(0)),
            // The extension is not matched, so --format and --compress do not reset the index.
            ("i0007_can0_2024-11-20T15-43-05Z.log.zst", "can0", Some(7)),
            // No width constraint: past the pad width, and hand-renamed below it.
            ("i10000_can0_1970-01-01T00-00-00Z.pcap", "can0", Some(10000)),
            ("i7_can0_WHATEVER CAN GO HERE", "can0", Some(7)),
            ("i0003_can_0_1970-01-01T00-00-00Z.log", "can_0", Some(3)),
            ("i18446744073709551615_can0_x.log", "can0", Some(u64::MAX)),
            ("i0000_can1_1970-01-01T00-00-00Z.log", "can0", None),
            // The can0/can01 prefix guard.
            ("i0000_can01_1970-01-01T00-00-00Z.log", "can0", None),
            ("0000_can0_1970-01-01T00-00-00Z.log", "can0", None),
            ("ixxxx_can0_1970-01-01T00-00-00Z.log", "can0", None),
            ("i_can0_1970-01-01T00-00-00Z.log", "can0", None),
            // One past u64::MAX is skipped rather than clamped.
            ("i18446744073709551616_can0_x.log", "can0", None),
            ("i0000_can0", "can0", None),
            ("candump.log", "can0", None),
        ];
        for (name, interface, expected) in vectors {
            assert_eq!(
                parse_index(name, interface),
                expected,
                "name={name} interface={interface}"
            );
        }
    }

    #[test]
    fn scan_of_an_empty_directory_is_empty() {
        let dir = TempDir::new().unwrap();
        let logs = scan(dir.path(), "can0");
        assert!(logs.is_empty(), "expected nothing, got {logs:?}");
    }

    #[test]
    fn scan_of_a_missing_directory_is_empty() {
        let dir = TempDir::new().unwrap();
        let missing = dir.path().join("nope");
        let logs = scan(&missing, "can0");
        assert!(logs.is_empty(), "expected nothing, got {logs:?}");
        assert!(!missing.exists(), "scanning must not create the directory");
    }

    #[test]
    fn scan_of_a_file_is_empty() {
        let dir = TempDir::new().unwrap();
        let file = dir.path().join("regular-file");
        std::fs::write(&file, b"file, not a directory").unwrap();

        let logs = scan(&file, "can0");
        assert!(logs.is_empty(), "expected nothing, got {logs:?}");
    }

    #[test]
    fn scan_orders_by_index_numerically_and_keeps_gaps() {
        let dir = TempDir::new().unwrap();
        touch(
            dir.path(),
            &["i10000_can0_x.log", "i7_can0_x.log", "i0003_can0_x.log"],
        );

        let logs = scan(dir.path(), "can0");
        assert_eq!(
            indexed_names(&logs),
            [
                (3, "i0003_can0_x.log"),
                (7, "i7_can0_x.log"),
                (10000, "i10000_can0_x.log"),
            ]
        );
    }

    #[test]
    fn scan_ignores_other_interfaces_and_foreign_files() {
        let dir = TempDir::new().unwrap();
        touch(
            dir.path(),
            &[
                "i0009_can1_x.log",
                "i0009_can01_x.log", // interface boundary is the trailing _
                "candump.log",
                "README",
            ],
        );

        let logs = scan(dir.path(), "can0");
        assert!(logs.is_empty(), "expected nothing, got {logs:?}");
    }

    #[test]
    fn scan_finds_a_directory_named_like_a_log() {
        // TODO: I think this is a bug, but I'm not sure if it's important enough to matter?
        let dir = TempDir::new().unwrap();
        std::fs::create_dir(dir.path().join("i0004_can0_x")).unwrap();
        let logs = scan(dir.path(), "can0");
        assert_eq!(indexed_names(&logs), [(4, "i0004_can0_x")]);
    }

    #[test]
    fn next_index_of_an_empty_directory_is_zero() {
        let dir = TempDir::new().unwrap();
        assert_eq!(next_index_in(dir.path(), "can0"), 0);
    }

    #[test]
    fn next_index_is_one_past_the_highest() {
        let dir = TempDir::new().unwrap();
        touch(dir.path(), &["i0000_can0_x.log", "i0003_can0_x.log"]);
        assert_eq!(next_index_in(dir.path(), "can0"), 4);
    }
}
